name: Auto-label PRs based on target branch

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  issues: write  # Esto permite modificar las etiquetas de los issues (PRs en este caso)

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add label based on target branch
        run: |
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
          if [ "$TARGET_BRANCH" == "main" ]; then
            LABEL="stable"
          elif [ "$TARGET_BRANCH" == "dev" ]; then
            LABEL="development"
          else
            LABEL="other"
          fi
          echo "Label: $LABEL"
        id: label

      - name: Add label to pull request using GitHub API
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            const label = '${{ steps.label.outputs.Label }}';
            const response = await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: [label],
            });
            console.log('Label added:', response.data);
